# This file is used to test the API while in development
:local = http://localhost:8000

# Valid register
POST :local/register
{
  "username": "rodrigo",
  "password": "pass"
}

# Invalid register: missing password
POST :local/register
{
  "username": "rodrigo"
}

# Invalid register: missing username
POST :local/register
{
  "password": "pass"
}

# Valid login
POST :local/login
{
  "username": "rodrigo",
  "password": "pass"
}

# Invalid login: unexisting user
POST :local/login
{
  "username": "askljdaskljd",
  "password": "pass"
}

# Invalid login: incorrect password
POST :local/login
{
  "username": "rodrigo",
  "password": "wrong"
}

# Get notes
GET :local/notes
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjF9.Kv3XT5YPALrPJCwYhhPB3uaemvEafa_ZfjjMpM6_DbY

# Get notes without authentication
GET :local/notes

# Get notes invalid token
GET :local/notes
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjF9.Kv3XT5YPALrPJCwYhhPB3uaemvEafa_ZfjjMpM6_DbI

# Create note
POST :local/notes
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjF9.Kv3XT5YPALrPJCwYhhPB3uaemvEafa_ZfjjMpM6_DbY
{
  "title": "Another note",
  "content": "Remember to do that"
}

# Create note without authentication
POST :local/notes
{
  "title": "Another note",
  "content": "Remember to do that"
}

# Create note with invalid tittle
POST :local/notes
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjF9.Kv3XT5YPALrPJCwYhhPB3uaemvEafa_ZfjjMpM6_DbY
{
  "title": "",
  "content": "This is a nice note"
}